.TH P-UAE 1
.SH NAME
\fBP-UAE\fR	\- a fork of UAE, the Ubiquitous Amiga Emulator.
.SH DESCRIPTION
\fBP-UAE\fR is a fork of E-UAE, the Ubiquitous Amiga Emulator, with an emulation
core based on WinUAE. It attempts to bring many of the great features of WinUAE
to non-Windows platforms. P-UAE was meant to be a Pandora Amiga emulator,
thus P-UAE, but later become the 'Portable' UAE.

For more information please browse the program documentation in
.IR /usr/share/doc/p-uae/docs .
.SH "SEE ALSO"
.BR uae (1)
